### ISSUE TITLE
No such file in directory & 'charmap' codec can't decode

### ISSUE THREAD

**Issue by hfleitas** [gunnarmorling/1brc#715]
When trying the non-authoritative Python script to generate the measurements file at `src/main/python/create_measurements.py`.

```
PS C:\hiram_msft\1brc> & C:/Users/hiramfleitas/AppData/Local/Microsoft/WindowsApps/python3.11.exe c:/hiram_msft/1brc/src/main/python/create_measurements.py 1_000_000_000
Traceback (most recent call last):
  File "c:\hiram_msft\1brc\src\main\python\create_measurements.py", line 160, in <module>
    main()
  File "c:\hiram_msft\1brc\src\main\python\create_measurements.py", line 153, in main
    weather_station_names = build_weather_station_name_list()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\hiram_msft\1brc\src\main\python\create_measurements.py", line 45, in build_weather_station_name_list
    with open('../../../data/weather_stations.csv', 'r') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '../../../data/weather_stations.csv'
```

I copied the data folder & its contents to the root of the C:\ drive to retry but yet fails due to charmap error. 

```
PS C:\hiram_msft\1brc> & C:/Users/hiramfleitas/AppData/Local/Microsoft/WindowsApps/python3.11.exe c:/hiram_msft/1brc/src/main/python/create_measurements.py 1_000_000_000
Traceback (most recent call last):
  File "c:\hiram_msft\1brc\src\main\python\create_measurements.py", line 160, in <module>
    main()
  File "c:\hiram_msft\1brc\src\main\python\create_measurements.py", line 153, in main
    weather_station_names = build_weather_station_name_list()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\hiram_msft\1brc\src\main\python\create_measurements.py", line 46, in build_weather_station_name_list
    file_contents = file.read()
                    ^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1776.0_x64__qbz5n2kfra8p0\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 398: character maps to <undefined>
```

**Comment by GambitKZ** [comment]
I have fixed that by adding the encoding to read/write operations (45 and 118 lines accordingly):
`with open('../../../data/weather_stations.csv', 'r', encoding="utf-8") as file:`
and
` with open("../../../data/measurements.txt", 'w', encoding="utf-8") as file:`

**Comment by pgr-lopes** [comment]
Not sure if this is still being maintained, but this problem persists on my end even after those changes. I added the encoding reference using the _io_ library and it seems to be working now. Example on line 45:

`with io.open('../../../data/weather_stations.csv', 'r', encoding="utf8") as file:`

**Comment by hfleitas** [comment]
I ended using WSL instead and the .sh commands in the instructions ran successfully, so I did not use the python unofficial script to generate the files. 

Here's my gist (in-official submission results): 
https://gist.github.com/hfleitas/060838e0e8eeb782dffead1de77ccd71#file-1brc-kql-L116

**Comment by Ale-Code404** [comment]
I got the same "No such file" error, but it worked when I ran it in the "src/main/python" directory.

`cd src/main/python && python create_measurements.py 1_000_000_000`
